### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by MonoAdrian23** [DimBis/KillRewards#4]
15:26:53] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 1" (EXCEPTION) in "plugins/KillRewards.phar/src/Dim9999/KillRewards/Main" at line 33

Latest Dev
Pocketmine 3.12.6
It happens when Items Set to blank
And Random Items to false

**Comment by DimBis** [comment]
Can you set the items value to "" instead of leaving it empty. `items: ""`
